DROP DATABASE IF EXISTS cryptodb;
CREATE DATABASE cryptodb;
USE cryptodb;
CREATE TABLE users (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(45) NULL,
  password VARCHAR(45) NULL,
  coin1 VARCHAR(45) NULL,
  coin2 VARCHAR(45) NULL,
  PRIMARY KEY (id)
);
